# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- master

stages:

- stage: BASICS
  displayName: 'BASICS'
  jobs:
  - job: job1
    displayName: COMMANDS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - script: pwd
  - job: job2
    displayName: 22
    steps: 
     - bash: uname -a

- stage: Maven
  displayName: 'Maven'
  jobs:
  - job: job3
    displayName: MavenBuild
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

- stage: Release
  displayName: 'ReleaseENV'
  jobs:
  - deployment: devenv1
    environment: dev-stage-env
  - job: job4
    displayName: Releaseenv
    pool:
      vmImage: 'ubuntu-latest'
    steps:

      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'dev-stage-env-surajakstest-default-1574936466909'
          namespace: 'dev'
          command: 'create'
          useConfigurationFile: true
          configuration: '/home/vsts/work/1/s/deployment.yaml'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'