# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- master

stages:

- stage: BASICS
  displayName: 'BASICS'
  jobs:
  - job: job1
    displayName: COMMANDS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - script: pwd
  - job: job2
    displayName: 22
    steps: 
     - bash: uname -a
    
  - job: 
    displayName: deployment
    steps:
     - 
   
- stage: BASICS1
  displayName: 'BASICS1'
  jobs:
  - job: scriptsh
    displayName: ssH
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - script: uname -a
