# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
stages:
- stage: basics
  displayName: 'BASICS'
  jobs:
  - job: trigger
    trigger:
    - master

- stage: pool
  displayName: 'VM IMAGE'
  jobs:
  - job: VM
    pool:
      vmImage: 'ubuntu-latest'


- stage: release
  displayName: RELESE ENVIRONMENT'
  jobs:
  - job: ENVIRONMENT
  environment: dev-env1