# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- master

stages:

- stage: BASICS
  displayName: 'BASICS'
  jobs:
  - job: scriptsh
    displayName: SHH
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - script: pwd

- stage: release
  displayName: 'RELESE env'
  jobs:
  - job: environ
    pool:
      vmImage: 'ubuntu-latest'
  environment: 'dev-env1'